services:
  api:
    build: .
    container_name: geo_tracker_api
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      DATABASE_URL: postgresql+asyncpg://server_admin:G_0d5th*3H$$10@10.11.52.96:5434/geospatial_tracking_system
      DATABASE_URL_SYNC: postgresql://server_admin:G_0d5th*3H$$10@10.11.52.96:5434/geospatial_tracking_system
      SECRET_KEY: change-this-in-production-use-a-long-random-string-at-least-32-chars
      ACCESS_TOKEN_EXPIRE_MINUTES: 480
      ALGORITHM: HS256
      ENVIRONMENT: production
    volumes:
      - .:/app
      - uploads:/app/uploads
      - C:/Users/Benjamin.shaibu/Downloads/SOKOTO_RESOURCES:/app/sokoto_data:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  redis:
    image: redis:7-alpine
    container_name: geo_tracker_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

volumes:
  uploads:
  redisdata:
