###############################################################################
# APK distribution bucket
#
# The Android build workflow (.github/workflows/app-build.yml) signs the
# release APK, uploads it here as `eritas-<versionName>-<versionCode>.apk`, then
# uses SSM to pull it onto the EC2 host and promote it to `eritas-latest.apk`,
# which the backend serves at `/apk`.
#
# NOTE: this bucket + its policy were originally created out-of-band (via the
# AWS CLI, 2026-06-08) and were NOT captured in Terraform — a `terraform plan`
# could not see them and a bring-back would have silently dropped APK
# publishing. Codified here 2026-08-04. The bucket name is the literal value of
# the `APK_S3_BUCKET` GitHub Actions variable; keep them in sync.
#
# Permissions model: the app-build workflow assumes the SAME github-deploy OIDC
# role (github-oidc.tf), which has NO S3 statements. Write access is granted
# resource-side, by the bucket policy below — keep it that way so the deploy
# role's identity policy stays minimal.
###############################################################################

resource "aws_s3_bucket" "apk" {
  bucket = "eha-mda-dashboard-apk"

  tags = { Name = "eha-mda-dashboard-apk" }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "apk" {
  bucket = aws_s3_bucket.apk.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# APKs are served to devices via short-lived presigned URLs generated by the
# backend — the bucket itself stays fully private.
resource "aws_s3_bucket_public_access_block" "apk" {
  bucket                  = aws_s3_bucket.apk.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

data "aws_iam_policy_document" "apk_bucket" {
  statement {
    sid    = "AllowDeployRoleApkStaging"
    effect = "Allow"
    principals {
      type        = "AWS"
      identifiers = [aws_iam_role.github_deploy.arn]
    }
    actions   = ["s3:PutObject", "s3:GetObject"]
    resources = ["${aws_s3_bucket.apk.arn}/*"]
  }
}

resource "aws_s3_bucket_policy" "apk" {
  bucket = aws_s3_bucket.apk.id
  policy = data.aws_iam_policy_document.apk_bucket.json

  # The public access block must exist before a bucket policy can reference a
  # principal, otherwise BlockPublicPolicy can reject it on first apply.
  depends_on = [aws_s3_bucket_public_access_block.apk]
}

output "apk_bucket" {
  description = "S3 bucket the APK build workflow publishes to. Mirror this into the APK_S3_BUCKET Actions variable."
  value       = aws_s3_bucket.apk.bucket
}
