#!/bin/bash
###############################################################################
# refresh-env.sh — fetch secrets from AWS Secrets Manager and write /opt/mda-dashboard/.env
#
# Runs at deploy time (and can be re-run any time secrets rotate).
# Uses the EC2 instance's IAM role for auth — no AWS keys on disk.
#
#   sudo /opt/mda-dashboard/refresh-env.sh
###############################################################################
set -euo pipefail

REGION=us-east-1
PROJECT=mda-dashboard
APP_DIR=/opt/mda-dashboard
ENV_FILE="$APP_DIR/.env"

ECR_REPO_URL="387526361725.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}"

# Helper: pull a JSON secret and emit `KEY=VALUE` lines from each top-level field.
fetch_json() {
    local secret_name="$1"
    aws secretsmanager get-secret-value \
        --region "$REGION" \
        --secret-id "$secret_name" \
        --query SecretString \
        --output text \
      | jq -r 'to_entries[] | "\(.key)=\(.value)"'
}

echo "Fetching secrets from AWS Secrets Manager..."

# Compose the .env file fresh — atomic write so the container never sees a partial file
TMP=$(mktemp)
{
    echo "# Auto-generated by refresh-env.sh — DO NOT EDIT BY HAND"
    echo "# Last refresh: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    echo "# Image tag for docker-compose.prod.yml"
    echo "ECR_REPO_URL=${ECR_REPO_URL}"
    echo ""
    echo "# Database URL (asyncpg + sync variants)"
    fetch_json "${PROJECT}/database-url-app"
    echo ""
    echo "# App secrets (JWT, Fernet, superadmin bootstrap)"
    fetch_json "${PROJECT}/app-secrets"
    echo ""
    echo "# CommCare HQ credentials (used by the sync service)"
    fetch_json "${PROJECT}/commcare"
    echo ""
    echo "# On-prem reverse-mirror target — surfaces the 'Mirror to on-prem'"
    echo "# button to superadmin in the admin panel. The mirror call itself"
    echo "# will only succeed if this host can reach the on-prem IP (i.e."
    echo "# via a Site-to-Site VPN); from a stock AWS VPC it will time out."
    echo "ONPREM_BACKUP_DATABASE_URL=$(aws secretsmanager get-secret-value \
        --region $REGION --secret-id ${PROJECT}/onprem-database-url \
        --query SecretString --output text 2>/dev/null || echo '')"
    echo ""
    echo "# Static config not in any secret"
    echo "ACCESS_TOKEN_EXPIRE_MINUTES=480"
    echo "ALGORITHM=HS256"
    echo "ENVIRONMENT=production"
} > "$TMP"

chmod 600 "$TMP"
mv "$TMP" "$ENV_FILE"
chown root:docker "$ENV_FILE" 2>/dev/null || true

echo "Wrote $ENV_FILE ($(wc -l < "$ENV_FILE") lines)"
