#!/bin/bash
###############################################################################
# dev-aws.sh — point the local docker-compose at AWS RDS via an SSH tunnel.
#
# Connects as `app_dev`, which has the same read/write grants as `app_prod`
# but a separate credential so dev/prod sessions can be told apart in the
# audit logs. Writes from the dev container land in the same RDS that prod
# reads from — that's intentional: it means new CommCare syncs / data work
# done from the dev laptop show up immediately at
# https://eha-mda-dashboard.ehealthnigeria.org without a redeploy.
#
# In short: this is dev *credentials*, not a dev *database*. Treat the data
# accordingly.
#
# Usage:
#   ./scripts/dev-aws.sh up        # opens tunnel, writes .env, starts compose
#   ./scripts/dev-aws.sh tunnel    # just opens the tunnel (foreground)
#   ./scripts/dev-aws.sh down      # closes tunnel, stops compose, restores .env.local
#
# Requires:
#   - aws CLI configured (you already have us-east-1 / 387526361725)
#   - ~/.ssh/mda-dashboard-prod private key
#   - VPN not required — bastion is publicly reachable from your IP allowlist
###############################################################################
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

REGION=us-east-1
PROJECT=mda-dashboard
SSH_KEY="$HOME/.ssh/${PROJECT}-prod"
BASTION_HOST="75.101.208.163"
RDS_ENDPOINT="mda-dashboard-db.cixghyv30jr7.us-east-1.rds.amazonaws.com"

# Local port that the tunnel listens on (chosen to not collide with any local Postgres)
LOCAL_PORT=25432

CMD="${1:-up}"

tunnel_pid_file="/tmp/${PROJECT}-tunnel.pid"

open_tunnel() {
    if [[ -f "$tunnel_pid_file" ]] && kill -0 "$(cat "$tunnel_pid_file")" 2>/dev/null; then
        echo "  Tunnel already open (pid $(cat "$tunnel_pid_file"))"
        return
    fi
    echo "  Opening SSH tunnel localhost:${LOCAL_PORT} → bastion → ${RDS_ENDPOINT}:5432..."
    ssh -f -N \
        -L "${LOCAL_PORT}:${RDS_ENDPOINT}:5432" \
        -i "$SSH_KEY" \
        -o ExitOnForwardFailure=yes \
        -o ServerAliveInterval=60 \
        -o StrictHostKeyChecking=accept-new \
        "ec2-user@${BASTION_HOST}"
    # Capture the pid of the newly-spawned ssh
    pgrep -f "ssh.*${LOCAL_PORT}:${RDS_ENDPOINT}" | head -1 > "$tunnel_pid_file"
    echo "  Tunnel open (pid $(cat "$tunnel_pid_file"))"
}

close_tunnel() {
    if [[ -f "$tunnel_pid_file" ]]; then
        pid=$(cat "$tunnel_pid_file")
        if kill -0 "$pid" 2>/dev/null; then
            kill "$pid"
            echo "  Tunnel closed (pid $pid)"
        fi
        rm -f "$tunnel_pid_file"
    fi
    pkill -f "ssh.*${LOCAL_PORT}:${RDS_ENDPOINT}" 2>/dev/null || true
}

write_env() {
    echo "  Fetching app_dev password from Secrets Manager..."
    local app_dev_password
    app_dev_password=$(aws secretsmanager get-secret-value \
        --region "$REGION" \
        --secret-id "${PROJECT}/app-dev-password" \
        --query SecretString --output text)

    # Back up an existing .env once
    if [[ -f .env && ! -f .env.local-onprem.bak ]]; then
        cp .env .env.local-onprem.bak
        echo "  Backed up existing .env → .env.local-onprem.bak"
    fi

    cat > .env <<ENVEOF
# Auto-generated by scripts/dev-aws.sh — DO NOT COMMIT
# Last write: $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Local docker-compose connects to AWS RDS as the read-only app_dev role
# via the SSH tunnel on localhost:${LOCAL_PORT}. host.docker.internal lets
# the container reach the Mac's tunnel port.

DATABASE_URL=postgresql+asyncpg://app_dev:${app_dev_password}@host.docker.internal:${LOCAL_PORT}/geospatial_tracking_system
DATABASE_URL_SYNC=postgresql://app_dev:${app_dev_password}@host.docker.internal:${LOCAL_PORT}/geospatial_tracking_system

# Dev-laptop session signing key (separate from prod). Only used for the
# local JWTs you mint when logged into the dev container — never sent to RDS.
SECRET_KEY=dev-secret-for-aws-tunnel-mode-not-prod
ACCESS_TOKEN_EXPIRE_MINUTES=480
ALGORITHM=HS256
ENVIRONMENT=development

# Fernet key — required so the encrypted sync_config password fields in RDS
# decrypt from the dev container. Same key prod uses.
SYNC_ENCRYPTION_KEY=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id "${PROJECT}/app-secrets" --query SecretString --output text | python3 -c "import sys,json; print(json.load(sys.stdin)['SYNC_ENCRYPTION_KEY'])")

# Optional reverse-mirror to on-prem. Leave blank to hide the button.
# When set, the admin panel surfaces a "Sync to on-prem" card that pushes
# RDS data back to the on-prem instance over the VPN. Example:
#   ONPREM_BACKUP_DATABASE_URL=postgresql://server_admin:PASS@10.11.52.96:5434/mda_pipeline
ONPREM_BACKUP_DATABASE_URL=${ONPREM_BACKUP_DATABASE_URL:-}
ENVEOF
    chmod 600 .env
    echo "  Wrote .env (RDS connection via app_dev / read-only)"
}

case "$CMD" in
    up)
        echo "▸ Dev-against-AWS-RDS mode"
        open_tunnel
        write_env
        echo "  Starting docker-compose (will read the new .env)..."
        docker compose up -d
        echo
        echo "✓ Local API at http://localhost:8090 — connected to AWS RDS as app_dev (read/write)"
        echo "  Heads up: writes from this container land in the SAME RDS prod reads from."
        echo "  Tail logs:  docker compose logs -f api"
        echo "  Stop mode:  ./scripts/dev-aws.sh down"
        ;;
    tunnel)
        echo "▸ Opening SSH tunnel only (foreground — Ctrl-C to close)"
        ssh -N -v \
            -L "${LOCAL_PORT}:${RDS_ENDPOINT}:5432" \
            -i "$SSH_KEY" \
            -o ExitOnForwardFailure=yes \
            -o ServerAliveInterval=60 \
            "ec2-user@${BASTION_HOST}"
        ;;
    down)
        echo "▸ Tearing down dev-AWS mode"
        docker compose down 2>/dev/null || true
        close_tunnel
        if [[ -f .env.local-onprem.bak ]]; then
            mv .env.local-onprem.bak .env
            echo "  Restored .env from backup (on-prem mode)"
        fi
        echo "✓ Done"
        ;;
    *)
        echo "Usage: $0 {up|tunnel|down}" >&2
        exit 1
        ;;
esac
